spring:
  application:
    name: bicimad-microservice

kafka:
  boostrap-servers: localhost:9092

bicimad:
  url: https://rbdata.emtmadrid.es:8443/BiciMad
  code: WEB.SERV.joseantonio.inigo@gmail.com
  passkey: A28B9528-6795-4C9F-993D-2B8AF39C899C

logging:
  level:
    org.apache.kafka: info